[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#1a1a19"
secondaryBackgroundColor = "#242423"
textColor = "#f4f3ee"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
