[theme]
base = "light"
primaryColor = "#2a78d6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f4f6"
textColor = "#262730"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
